### PR TITLE
Fix #86: Upload on docker failed

### LINKED ISSUE #86: Error when uploading a newgrf to bananas-api running in docker
If you run the bananas-api as suggested in the readme using: 
```bash
docker run --rm -p 127.0.0.1:8080:80 -p 127.0.0.1:1080:1080 -v "${BANANAS_COMMON}/local_storage:/code/local_storage" -v "${BANANAS_COMMON}/BaNaNaS:/code/BaNaNaS" openttd/bananas-api:local
```
Upload of a newgrf fails with the following error: 
```
OSError: [Errno 18] Invalid cross-device link
```

The issue is that the temporary upload path and the local_storage path are not on the same physical device (one is inside the virtual file system of the docker container, while the other is on a volume mounted on the host). 

According to the documentation I have found, [shutil.move](https://docs.python.org/3/library/shutil.html#shutil.move) is the correct function to use if you are moving between file systems.

### PR DESCRIPTION
**Pull request by erenes**
Resolves issue #86 Error when uploading a newgrf to bananas-api running in docker

### CODE REVIEW

**Comment by TrueBrain** [comment]
Just as a quick FYI, we don't need an issue for a Pull Request. Always feel free to just make the Pull Request, without an issue. Saves you a bit of time / work :)

**Comment by erenes** [comment]
Haha, tell that to my managers at work ;-) 
I'll keep it in mind for future PRs :)

**Comment by TrueBrain** [comment]
> 
> 
> Haha, tell that to my managers at work ;-)
> I'll keep it in mind for future PRs :)

We try to keep things fun instead :P :P :P :D

**Review by TrueBrain — DISMISSED** [review]
One would assume Python handles that for you ...

**Comment by erenes** [comment]
I did that this weekend using the button in github, but then it merges master to my branch instead of rebases properly, and of course, will not use the right commit-message format ;-) 

Anyway, done rebased :)

**Review by TrueBrain — APPROVED** [review]

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
